### ISSUE TITLE
Pipeline with pseudoalignment quantification tools

### ISSUE THREAD

**Issue by ktmf1991** [gagneurlab/OUTRIDER#15]
Hi,

Just found this wonderful tool which suits really well with what I am working on. However, in our lab we use kallisto for quantification. The counts after tximport are not integer and I cannot proceed. 

Is it possible that I can get my way around it without redoing the alignment, e.g. using TPM value and starts at some point before adjusting for cofounding factor/batch effect?

Many thanks

**Comment by brechtmann** [comment]
Hi,

unfortunately you cannot use TPM values. Our statistical model requires your inputs to be counts. 
Further, you should not have to worry about confounding factors and batch effects as we automatically control for them.  Just use summarizeOverlaps or HT-Seq to obtain a count table.

Cheers,
Felix

**Comment by c-mertes** [comment]
Hi @ktmf1991,

a bit late but maybe it still helps. Since you use kallisto for quantification you could also start with the estimated counts provided by kallisto. Based on the manual after running `kallisto quant`, you should have the `abundances.tsv` file that contains the estimated counts or est_counts (https://pachterlab.github.io/kallisto/manual.html). Those should be integers and almost as good as raw counts for the stats in OUTRIDER.

If you do not have any further questions for this topic, I would close this issue end of the week.
